package org.zipper.modules.account.constant

object Permissions {

    const val LineList = "app:account:line:list"
    const val LineAdd = "app:account:line:add"
    const val LineEdit = "app:account:line:edit"
    const val LineDelete = "app:account:line:delete"
    const val LineUpload = "app:account:line:upload"
    const val LineUnbind = "app:account:line:unbind"
    const val LineRecord = "app:account:line:record:list"
    const val LineDispatch = "app:account:line:dispatch"
    const val LineExport = "app:account:line:export"


    const val PairsList = "app:account:pairs:list"
    const val PairsAdd = "app:account:pairs:add"
    const val PairsEdit = "app:account:pairs:edit"
    const val PairsDelete = "app:account:pairs:delete"
    const val PairsUpload = "app:account:pairs:upload"
    const val PairsUnbind = "app:account:pairs:unbind"
    const val PairsRecord = "app:account:pairs:record:list"
    const val PairsDispatch = "app:account:pairs:dispatch"
    const val PairsExport = "app:account:pairs:export"

    const val Ws1List = "app:account:ws1:list"
    const val Ws1Add = "app:account:ws1:add"
    const val Ws1Edit = "app:account:ws1:edit"
    const val Ws1Delete = "app:account:ws1:delete"
    const val Ws1Upload = "app:account:ws1:upload"
    const val Ws1Unbind = "app:account:ws1:unbind"
    const val Ws1Record = "app:account:ws1:record:list"
    const val Ws1Dispatch = "app:account:ws1:dispatch"
    const val Ws1Export = "app:account:ws1:export"

    const val Ws2List = "app:account:ws2:list"
    const val Ws2Add = "app:account:ws2:add"
    const val Ws2Edit = "app:account:ws2:edit"
    const val Ws2Delete = "app:account:ws2:delete"
    const val Ws2Upload = "app:account:ws2:upload"
    const val Ws2Unbind = "app:account:ws2:unbind"
    const val Ws2Record = "app:account:ws2:record:list"
    const val Ws2Dispatch = "app:account:ws2:dispatch"
    const val Ws2Export = "app:account:ws2:export"

    const val Ws3List = "app:account:ws3:list"
    const val Ws3Add = "app:account:ws3:add"
    const val Ws3Edit = "app:account:ws3:edit"
    const val Ws3Delete = "app:account:ws3:delete"
    const val Ws3Upload = "app:account:ws3:upload"
    const val Ws3Unbind = "app:account:ws3:unbind"
    const val Ws3Record = "app:account:ws3:record:list"
    const val Ws3Dispatch = "app:account:ws3:dispatch"
    const val Ws3Export = "app:account:ws3:export"

    const val Ws4List = "app:account:ws4:list"
    const val Ws4Add = "app:account:ws4:add"
    const val Ws4Edit = "app:account:ws4:edit"
    const val Ws4Delete = "app:account:ws4:delete"
    const val Ws4Upload = "app:account:ws4:upload"
    const val Ws4Unbind = "app:account:ws4:unbind"
    const val Ws4Record = "app:account:ws4:record:list"
    const val Ws4Dispatch = "app:account:ws4:dispatch"
    const val Ws4Export = "app:account:ws4:export"

    const val Ws5List = "app:account:ws5:list"
    const val Ws5Add = "app:account:ws5:add"
    const val Ws5Edit = "app:account:ws5:edit"
    const val Ws5Delete = "app:account:ws5:delete"
    const val Ws5Upload = "app:account:ws5:upload"
    const val Ws5Unbind = "app:account:ws5:unbind"
    const val Ws5Record = "app:account:ws5:record:list"
    const val Ws5Dispatch = "app:account:ws5:dispatch"
    const val Ws5Export = "app:account:ws5:export"

    const val Ws6List = "app:account:ws6:list"
    const val Ws6Add = "app:account:ws6:add"
    const val Ws6Edit = "app:account:ws6:edit"
    const val Ws6Delete = "app:account:ws6:delete"
    const val Ws6Upload = "app:account:ws6:upload"
    const val Ws6Unbind = "app:account:ws6:unbind"
    const val Ws6Record = "app:account:ws6:record:list"
    const val Ws6Dispatch = "app:account:ws6:dispatch"
    const val Ws6Export = "app:account:ws6:export"

    const val Ws7List = "app:account:ws7:list"
    const val Ws7Add = "app:account:ws7:add"
    const val Ws7Edit = "app:account:ws7:edit"
    const val Ws7Delete = "app:account:ws7:delete"
    const val Ws7Upload = "app:account:ws7:upload"
    const val Ws7Unbind = "app:account:ws7:unbind"
    const val Ws7Record = "app:account:ws7:record:list"
    const val Ws7Dispatch = "app:account:ws7:dispatch"
    const val Ws7Export = "app:account:ws7:export"

    const val WsSearch = "app:account:ws:search"
}