version: '3.4'

networks:
  ry:
    driver: bridge

services:
  ry-mysql:
    image: mysql:8.0.33
    container_name: ry-mysql
    build:
      context: ./mysql
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 初始化数据库(后续的初始化sql会在这个库执行)
      MYSQL_DATABASE: ${SQL_DATABASE:-ry_kt}
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD:-zzp@949389}
      MYSQL_USER: ${SQL_USER:-zipper}
      MYSQL_PASSWORD: ${SQL_PASSWORD:-zzp@949389}
    ports:
      - "3308:3306"
    volumes:
      # 数据挂载
      - ./mysql/data/:/var/lib/mysql/
      # 配置挂载
      - ./mysql/conf/:/etc/mysql/conf.d/
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    networks:
      - ry
  ## redis
  ry-redis:
    image: redis:6.2.12
    container_name: ry-redis
    restart: unless-stopped
    build:
      context: ./redis
    ports:
      - "6378:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - ./redis/conf:/home/ruoyi/redis/config:rw
      # 数据文件
      - ./redis/data/:/home/ruoyi/redis/data/:rw
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    networks:
      - ry

  ry-server:
    image: ry-server
    container_name: ry-server
    restart: unless-stopped
    build:
      context: ./server
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      ARGS:
        --spring.redis.host=ry-redis
        --user.home=/home/ruoyi
        --spring.datasource.dynamic.datasource.master.url=-jdbc:mysql://ry-mysql:3306/${SQL_DATABASE:-ry_kt}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
        --spring.datasource.dynamic.datasource.master.username=${SQL_USER:-zipper}
        --spring.datasource.dynamic.datasource.master.password=${SQL_PASSWORD:-zzp@949389}
    volumes:
      - ./server:/home/ruoyi:rw
      - ./server/ruoyi-server.jar:/home/yudao/ruoyi-server.jar
    depends_on:
      - ry-mysql
      - ry-redis
    privileged: true
    networks:
      - ry


  ry-nginx:
    image: nginx:1.23.4
    container_name: nginx-web
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      # 证书映射
      - ./nginx/cert:/etc/nginx/cert
      # 配置文件映射
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # 页面目录
      - ./nginx/html:/usr/share/nginx/html
      # 日志目录
      - ./nginx/log:/var/log/nginx
    privileged: true
    networks:
      - ry