export enum Permission {
  LineList = "app:account:line:list",
  LineAdd = "app:account:line:add",
  LineEdit = "app:account:line:edit",
  LineDelete = "app:account:line:delete",
  LineUpload = "app:account:line:upload",
  LineUnbind = "app:account:line:unbind",
  LineRecord = "app:account:line:record:list",
  LineDispatch = "app:account:line:dispatch",
  LineExport = "app:account:line:export",

  // pairs
  PairsList = "app:account:pairs:list",
  PairsAdd = "app:account:pairs:add",
  PairsEdit = "app:account:pairs:edit",
  PairsDelete = "app:account:pairs:delete",
  PairsUpload = "app:account:pairs:upload",
  PairsUnbind = "app:account:pairs:unbind",
  PairsRecord = "app:account:pairs:record:list",
  PairsDispatch = "app:account:pairs:dispatch",
  PairsExport = "app:account:pairs:export",

  Ws1List = "app:account:ws1:list",
  Ws1Add = "app:account:ws1:add",
  Ws1Edit = "app:account:ws1:edit",
  Ws1Delete = "app:account:ws1:delete",
  Ws1Upload = "app:account:ws1:upload",
  Ws1Unbind = "app:account:ws1:unbind",
  Ws1Record = "app:account:ws1:record:list",
  Ws1Dispatch = "app:account:ws1:dispatch",
  Ws1Export = "app:account:ws1:export",

  Ws2List = "app:account:ws2:list",
  Ws2Add = "app:account:ws2:add",
  Ws2Edit = "app:account:ws2:edit",
  Ws2Delete = "app:account:ws2:delete",
  Ws2Upload = "app:account:ws2:upload",
  Ws2Unbind = "app:account:ws2:unbind",
  Ws2Record = "app:account:ws2:record:list",
  Ws2Dispatch = "app:account:ws2:dispatch",
  Ws2Export = "app:account:ws2:export",

  Ws3List = "app:account:ws3:list",
  Ws3Add = "app:account:ws3:add",
  Ws3Edit = "app:account:ws3:edit",
  Ws3Delete = "app:account:ws3:delete",
  Ws3Upload = "app:account:ws3:upload",
  Ws3Unbind = "app:account:ws3:unbind",
  Ws3Record = "app:account:ws3:record:list",
  Ws3Dispatch = "app:account:ws3:dispatch",
  Ws3Export = "app:account:ws3:export",

  Ws4List = "app:account:ws4:list",
  Ws4Add = "app:account:ws4:add",
  Ws4Edit = "app:account:ws4:edit",
  Ws4Delete = "app:account:ws4:delete",
  Ws4Upload = "app:account:ws4:upload",
  Ws4Unbind = "app:account:ws4:unbind",
  Ws4Record = "app:account:ws4:record:list",
  Ws4Dispatch = "app:account:ws4:dispatch",
  Ws4Export = "app:account:ws4:export",

  Ws5List = "app:account:ws5:list",
  Ws5Add = "app:account:ws5:add",
  Ws5Edit = "app:account:ws5:edit",
  Ws5Delete = "app:account:ws5:delete",
  Ws5Upload = "app:account:ws5:upload",
  Ws5Unbind = "app:account:ws5:unbind",
  Ws5Record = "app:account:ws5:record:list",
  Ws5Dispatch = "app:account:ws5:dispatch",
  Ws5Export = "app:account:ws5:export",

  Ws6List = "app:account:ws6:list",
  Ws6Add = "app:account:ws6:add",
  Ws6Edit = "app:account:ws6:edit",
  Ws6Delete = "app:account:ws6:delete",
  Ws6Upload = "app:account:ws6:upload",
  Ws6Unbind = "app:account:ws6:unbind",
  Ws6Record = "app:account:ws6:record:list",
  Ws6Dispatch = "app:account:ws6:dispatch",
  Ws6Export = "app:account:ws6:export",

  Ws7List = "app:account:ws7:list",
  Ws7Add = "app:account:ws7:add",
  Ws7Edit = "app:account:ws7:edit",
  Ws7Delete = "app:account:ws7:delete",
  Ws7Upload = "app:account:ws7:upload",
  Ws7Unbind = "app:account:ws7:unbind",
  Ws7Record = "app:account:ws7:record:list",
  Ws7Dispatch= "app:account:ws7:dispatch",
  Ws7Export = "app:account:ws7:export",

  List = "app:account:list",
  Add = "app:account:add",
  Upload = "app:account:upload",
  Edit = "app:account:edit",
  Delete = "app:account:delete",
  Unbind = "app:account:unbind",
  Record = "app:account:record:list",
  Dispatch = "app:account:dispatch",
  Export = "app:account:export",
}

export enum DataClassify {
  Line = 1,
  Pairs = 2,
  Ws1 = 3,
  Ws2 = 4,
  Ws3 = 5,
  Ws4 = 6,
  Ws5 = 7,
  Ws6 = 8,
  Ws7 = 9,

}
